### ISSUE TITLE
Vue 3 without options API

### ISSUE THREAD

**Issue by dacoto** [danielstgt/laravel-mix-svg-vue#6]
If we are using vue3 with the options api disabled, it doesn't work, as the mixins are for the old options api, which is a temporary transition between vue 2 and vue 3.

**Comment by danielstgt** [comment]
Could you share a code example? I couldn't find anything how to disable the options API explicitly, I want to make sure I'm debugging the right case. Sorry if I went too fast through the docs and missed that.

**Comment by dacoto** [comment]
```
.webpackConfig({
    plugins: [
      new webpack.DefinePlugin({
        __VUE_OPTIONS_API__: false,
        __VUE_PROD_DEVTOOLS__: false
      })
    ]
  })
```

**Comment by danielstgt** [comment]
This issue was very helpful, I learned a lot about the composition API - thanks!

There is a new release available ([v0.3.2](https://github.com/danielstgt/laravel-mix-svg-vue/releases/tag/v0.3.2)) that uses exclusively the composition API for the `svg-vue3` dependency.

I've tested it with your provided config to disable the options API. If you still encounter any problems, feel free to reopen this issue.

**Comment by dacoto** [comment]
[Vue warn]: Mixins are only available in builds supporting Options API

IDEA [Check if vue3 is active and don't declare the mixin.] ¿?¿

Good Job! with the refactor.

**Comment by danielstgt** [comment]
Are you sure that warning comes from this Plugin/Library? There are no mixins used.

Could you share a [CodeSandbox](https://codesandbox.io/) example with a minimal setup that shows this warning?
